[platformio]
default_envs =  gateway

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -D CORE_DEBUG_LEVEL=1
lib_deps =
    sandeepmistry/LoRa

; =========================================================
; NODE: sensors + LoRa telemetry + ACK/command + adaptive sleep
; =========================================================
[env:node]
build_src_filter =
    -<*>
    +<node_main.cpp>
    +<dht22_sensor.cpp>
    +<soil_moisture.cpp>
    +<packet_protocol.cpp>

; =========================================================
; GATEWAY: LoRa RX/TX + local dashboard/export + ThingsBoard HTTP
; =========================================================
[env:gateway]
build_src_filter =
    -<*>
    +<gateway_main.cpp>
    +<gateway_state.cpp>
    +<gateway_logic.cpp>
    +<gateway_cloud.cpp>
    +<gateway_lora.cpp>
    +<gateway_web.cpp>
    +<packet_protocol.cpp>
