; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; ================== GLOBAL ==================
[platformio]
default_envs = test_dht22   ; đổi dòng này để chọn module chạy

; ================== BASE CONFIG ==================
[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; ================== TEST SOIL ==================
[env:test_soil_moisture]
build_src_filter =
    -<*>
    +<Test_sensor/Test_Soil_Moisture/>

; ================== TEST DHT22 ==================
[env:test_dht22]
build_src_filter =
    -<*>
    +<Test_sensor/Test_DHT22/>