; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; ================== GLOBAL ==================
[platformio]
default_envs = test_pt100   ; đổi dòng này để chọn module chạy

; ================== BASE CONFIG ==================
[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; ================== TEST MPU6050 ==================
[env:test_mpu6050]
build_src_filter =
    -<*>                                  ; loại toàn bộ src
    +<Test_sensor/Test_MPU6050/>           ; chỉ build folder này

; ================== TEST SOIL ==================
[env:test_soil_moisture]
build_src_filter =
    -<*>
    +<Test_sensor/Test_Soil_Moisture/>

; ================== TEST PT100 ==================
[env:test_pt100]
build_src_filter =
    -<*>
    +<Test_sensor/Test_PT100/>